name: es-manager

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: es-cluster
    environment:
      - node.name=es-node-1
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - es-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  es-app:
    build: .
    container_name: es-app
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=3501
      - ES_HOST=elasticsearch
      - ES_PORT=9200
      - ES_PROTOCOL=http
      - CORS_ORIGIN=*
      - SERVER_PORT=3501
    ports:
      - "3502:80"      # 前端nginx端口
      - "3501:3501"    # 后端API端口
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - es-network
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3501/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  es_data:
    driver: local

networks:
  es-network:
    driver: bridge