name: Build and Release Electron App

on:
  push:
    branches: [ main, develop ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write
  
jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [windows-latest]  # 先只构建 Windows
        node-version: [20]
        
    steps:
    - name: Check out Git repository
      uses: actions/checkout@v4

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Build web application
      run: npm run build:prod

    - name: Build Electron app (Windows)
      run: npm run dist:win:prod

    - name: Upload artifacts (Windows)
      uses: actions/upload-artifact@v4
      with:
        name: windows-builds
        path: |
          dist-electron/*.exe
          dist-electron/*.msi
        retention-days: 30

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - name: Check out Git repository
      uses: actions/checkout@v4

    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: ./artifacts

    - name: Display structure of downloaded files
      run: ls -R ./artifacts

    - name: Create Release with Assets
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        name: ES Manager ${{ github.ref_name }}
        draft: false
        prerelease: false
        body: |
          ## ES Manager ${{ github.ref_name }}
          
          ### 新特性 / New Features
          - Electron Windows 桌面应用
          - Elasticsearch 可视化管理工具
          
          ### 支持平台 / Supported Platforms  
          - **Windows**: 64-bit (x64)
          
          ### 安装说明 / Installation
          - **Windows**: 下载 `.exe` 安装程序
        files: |
          ./artifacts/windows-builds/*

