name: Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  coverage:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run tests with coverage
      run: |
        NODE_OPTIONS="--experimental-vm-modules" npm run test:backend:coverage
        npm run test:frontend:coverage
      env:
        NODE_ENV: test
    
    - name: Merge coverage reports
      run: |
        npm install -g lcov-result-merger
        lcov-result-merger 'coverage/**/lcov.info' 'coverage/lcov.info'
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage/lcov.info
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false
    
    - name: Generate coverage badge
      run: |
        npm install -g coverage-badge-creator
        coverage-badge-creator --report ./coverage/lcov.info --output ./coverage/badge.svg
    
    - name: Upload coverage badge
      uses: actions/upload-artifact@v3
      with:
        name: coverage-badge
        path: coverage/badge.svg
    
    - name: Comment PR with coverage
      if: github.event_name == 'pull_request'
      uses: 5monkeys/cobertura-action@master
      with:
        path: coverage/lcov.info
        minimum_coverage: 75
        fail_below_threshold: false
        show_line: true
        show_branch: true
        show_class_names: true
        show_missing: true
        show_skip: true
        only_changed_files: true