name: Test

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run lint
        run: npm run lint || echo "No lint script defined"
      
      - name: Run tests
        run: npm test || echo "No test script defined"
      
      - name: Build project
        run: npm run build
      
      - name: Check build output
        run: |
          if [ -d "dist" ]; then
            echo "Build successful - dist folder exists"
            ls -la dist/
          else
            echo "Build failed - dist folder not found"
            exit 1
          fi